[project]
name = "hirestream-match"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.7,<3.14"
dependencies = [
    "openai>=2.7.1",
    "pdfplumber>=0.11.7",
    "streamlit>=1.51.0",
]
